[features]
seeds = false
[programs.localnet]
solana_shop = "ShoPVoCg1wWKuNnMxqekeHfvfNkUBjAyUPbtL1AoFAP"
[programs.devnet]
solana_shop = "5VggK8ZBCDGCRQ9PruBwfTr6u6RweXKxHJpkEcrqk5W7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./account/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
